server:
  port: 8101

spring:
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

